# Generated by Django 6.0.4 on 2026-06-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouchpointTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touchpoint_number', models.IntegerField(unique=True)),
                ('subject', models.CharField(default='', max_length=500)),
                ('body', models.TextField(default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('signature', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='touchpoint_attachments/')),
                ('signature_image', models.FileField(blank=True, help_text='Inline signature image (referenced via cid:signature_tpN).', null=True, upload_to='touchpoint_signatures/')),
                ('days_after_previous', models.IntegerField(default=7)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'touchpoint_templates',
                'ordering': ['touchpoint_number'],
            },
        ),
    ]
