# Generated by Django 6.0.3 on 2026-06-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contact_alter_otp_id_alter_touchpointtemplate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendjob',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
