# Generated by Django 6.0.3 on 2026-06-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sendjob_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchpointtemplate',
            name='daily_send_limit',
            field=models.IntegerField(default=0, help_text='Max emails to send per day (0 = send all at once)'),
        ),
    ]
