# Generated by Django 6.0.3 on 2026-06-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contact_opt_out_reason_savedtestemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='accounts.importgroup')),
            ],
            options={
                'db_table': 'segments',
                'ordering': ['name'],
                'unique_together': {('import_group', 'name')},
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='accounts.segment'),
        ),
    ]
