# Generated by Django 6.0.3 on 2026-06-14 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_segment_contact_segment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('subject', models.CharField(default='', max_length=500)),
                ('body_html', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='', help_text='Plain-text fallback')),
                ('signature', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sendjob',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Optional reusable template whose content overrides the touchpoint for this send.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_jobs', to='accounts.emailtemplate'),
        ),
    ]
