# Generated by Django 6.0.3 on 2026-06-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_emailtemplate_sendjob_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='template_attachments/'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='signature_image',
            field=models.FileField(blank=True, help_text='Inline signature image (referenced via cid:signature_tplN).', null=True, upload_to='template_signatures/'),
        ),
    ]
