# Generated by Django 6.0.3 on 2026-06-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_emailtemplate_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='opt_out_text',
            field=models.TextField(blank=True, default="If you'd prefer not to receive further communication from us, you can opt out here.", help_text='Opt-out sentence rendered as a clickable unsubscribe link at the bottom of the email.'),
        ),
        migrations.AddField(
            model_name='touchpointtemplate',
            name='opt_out_text',
            field=models.TextField(blank=True, default="If you'd prefer not to receive further communication from us, you can opt out here.", help_text='Opt-out sentence shown at the bottom of the email; rendered as a clickable unsubscribe link.'),
        ),
    ]
