# Generated by Django 6.0.3 on 2026-06-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_emailtemplate_opt_out_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('undeliverable', 'Undeliverable'), ('opted_out', 'Opt-out'), ('moved_to_hubspot', 'Moved to HubSpot'), ('bounced', 'Bounced')], default='active', max_length=20),
        ),
    ]
