# Generated by Django 6.0.3 on 2026-06-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='positive_replies',
            field=models.IntegerField(default=0, help_text='Manually tracked count of positive replies for this segment.'),
        ),
    ]
