# Generated by Django 6.0.3 on 2026-08-07 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_segment_positive_replies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'custom_fields',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Values for user-defined columns, keyed by CustomField name.'),
        ),
        migrations.AddField(
            model_name='touchpointtemplate',
            name='goodbye_for',
            field=models.IntegerField(blank=True, help_text='Touchpoint number this goodbye belongs to; null = campaign-wide fallback.', null=True),
        ),
        migrations.AddField(
            model_name='touchpointtemplate',
            name='is_goodbye',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Serialized flow: touchpoints with waits and goodbye content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flow_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReactivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='', help_text='Where the attempt came from, e.g. "Import: contacts.xlsx"', max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='The incoming row data that was blocked')),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('kept_opted_out', 'Kept opted out')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivation_requests', to='accounts.contact')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reactivation_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=0, help_text='Max recipients for this run (0 = all eligible)')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('import_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.importgroup')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.segment')),
                ('send_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_send', to='accounts.sendjob')),
                ('template', models.ForeignKey(blank=True, help_text='Optional library template whose content overrides the touchpoint.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.emailtemplate')),
                ('touchpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sends', to='accounts.touchpointtemplate')),
            ],
            options={
                'db_table': 'scheduled_sends',
                'ordering': ['scheduled_for'],
            },
        ),
    ]
