# Generated by Django 6.0.3 on 2026-08-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customfield_contact_custom_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'campaign_groups',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='touchpointtemplate',
            name='touchpoint_number',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_campaign',
            field=models.ForeignKey(blank=True, help_text='The campaign whose journey this contact is on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_contacts', to='accounts.campaign'),
        ),
        migrations.AddField(
            model_name='touchpointtemplate',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints', to='accounts.campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='touchpointtemplate',
            unique_together={('campaign', 'touchpoint_number')},
        ),
        migrations.AddField(
            model_name='campaign',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.campaigngroup'),
        ),
    ]
