# Generated by Django 6.0.3 on 2026-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_default_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledsend',
            name='batch_key',
            field=models.CharField(blank=True, default='', help_text='Rows scheduled together (one campaign flow) share a key — shown as one card.', max_length=40),
        ),
    ]
