# Generated by Django 6.0.3 on 2026-08-07 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_scheduledsend_batch_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendjob',
            name='touchpoint',
            field=models.ForeignKey(blank=True, help_text='Null when the touchpoint was later deleted — past sends keep their history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_jobs', to='accounts.touchpointtemplate'),
        ),
    ]
