# Generated by Django 6.0.3 on 2026-08-08 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_sendjob_touchpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_automated',
            field=models.BooleanField(default=False, help_text='Normal campaigns are sent by hand; automated ones enrol new contacts themselves.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='segment',
            field=models.ForeignKey(blank=True, help_text='Default audience — pre-filled on every send; optional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='accounts.segment'),
        ),
        migrations.AddField(
            model_name='campaigngroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='touchpointtemplate',
            name='send_time',
            field=models.TimeField(blank=True, help_text='Pins the clock time it sends at — e.g. wait 1 week, then at 9:00 AM.', null=True),
        ),
        migrations.AddField(
            model_name='touchpointtemplate',
            name='wait_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Notes (optional)'),
        ),
    ]
