# Generated by Django 6.0.3 on 2026-08-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_campaign_is_automated_campaign_segment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchpointtemplate',
            name='signature_image_height',
            field=models.IntegerField(default=90, help_text='Rendered height in px (0 = auto, keeps proportions).'),
        ),
        migrations.AddField(
            model_name='touchpointtemplate',
            name='signature_image_width',
            field=models.IntegerField(default=0, help_text='Rendered width in px (0 = auto, keeps proportions).'),
        ),
    ]
