# Generated by Django 6.0.3 on 2026-08-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_touchpointtemplate_signature_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendjob',
            name='target_summary',
            field=models.CharField(blank=True, default='', help_text="Human summary of who this run targeted, e.g. 'South African Data · Gauteng'.", max_length=300),
        ),
    ]
