# Generated by Django 6.0.3 on 2026-08-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_sendjob_target_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchpointtemplate',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Optional custom label shown instead of "Touchpoint N".', max_length=200),
        ),
    ]
