# Generated by Django 6.0.3 on 2026-08-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_tag_contact_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='import_group',
            field=models.ForeignKey(blank=True, help_text='Default audience group — used when a send/schedule picks no audience.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='accounts.importgroup'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='Default audience tag — only contacts carrying it are targeted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='accounts.tag'),
        ),
        migrations.AddField(
            model_name='scheduledsend',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tag'),
        ),
    ]
